markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : FENGWEI.WANG 
production_url : http://wfwei.github.io
description: "Througths, flamewars, utilities, tutorials, codes, projects and other things by FengweiWang."
disqus_shortname: wfwei 
analytics: UA-30211938-1
gauges: 
author :
  name : FengweiWang
  github : wfwei 
  twitter : wfwei
